repos:
  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet format
        entry: dotnet format
        language: system
        types: [text]
        args: ["RadarMoves.sln"]
        pass_filenames: false
        always_run: true
